
version: "3.8"

services:
  postgres:
    container_name: postgres-main
    image: postgres
    volumes:
      - pg-data4:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: golang-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data4:
